# Generated by Django 3.2.6 on 2021-08-30 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0006_rename_employee_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('ancho', models.FloatField()),
                ('alto', models.FloatField()),
                ('grosor', models.FloatField()),
                ('peso', models.FloatField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='login.customer')),
            ],
        ),
    ]
