# Generated by Django 3.2.6 on 2021-08-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210827_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(max_length=11),
        ),
    ]
