# Generated by Django 3.2.6 on 2021-08-27 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_user_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombres',
        ),
    ]
