# Generated by Django 3.2.6 on 2021-08-28 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20210827_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login.user')),
                ('phone_number', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login.user')),
                ('phone_number', models.CharField(max_length=20)),
                ('tradename', models.CharField(max_length=255)),
                ('ruc', models.CharField(max_length=100)),
                ('business_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='es_cliente',
            new_name='is_business',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='es_empresa',
            new_name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='whatsapp',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
