# Generated by Django 3.2.6 on 2021-08-28 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20210828_1614'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Business',
        ),
    ]
